spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registeruser
    username: developer
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: create 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB


image:
  path: C:/Users/Public/Pictures/images/

